# design a new class - inspector
	# initialize with
		# attribute 1 - age (defaulted)
		# attribute 2 - caffeine consumption preference (defaulted to coffee)
		# attribute 3 - gender (setter)
		# attribute 4 - ethnicity (getter)
		# attribute 5 - cases solved (randomly generated by rank)
		# attribute 6 - rank (randomly generated or user input)
		# attribute 7 - name (setter)
		# attribute 8 - alcohol tollerance between 1 and 10 (getter)
	# methods 
		# get promoted
			# promotion will advance rank to the index in rank array, 
			# if already at max rank then retires
		# question the string argument
			# puts Where were you between 5 and 7 pm last friday
		# paperwork
			# puts "I have a ton of paperwork to complete"
		# pub with argument for how many beers to consume
			# how many beers to consume.times 
				# if rank is above certain level then
					# puts I think that would be setting a poor example to your colleagues
					# puts maybe you should try your hand at a round of golf with your peers
				# else rank is at or below certain level then
					# for each conumption
						# puts "name" takes a drink
						# case drinks
						# when already past 2 then 
							# puts "name" starts to feel a little tipsy
						# when already past 5 then
							# puts "name" starts to hiccup and appear quite well off
							# alcohol tollerance + 1
						# when already past 8 then
							# puts "name" appears very drunk and is slurring their words
							# alcohol tollerance + 1 
						# when 10 then 
							# puts "name" blacks out
							# alcohol tollerance + 1
						#end
					#end 
					#puts "name" retires to their residence and concludes their night out
			# break if drinks > alcohol tollerance
		# solve another case!
			# increase case solved by 1 
			# puts congratulations "name" on solving another case!
		# celebrate birthday
			# increase age by 1
		# ccpref 
			# puts "name" prefers ccpref
	# attr_accessor name, gender, caffeine consumption preference
	# attr_reader ethnicity, age, cases solved, rank, alcohol tollerance
# end

class Inspector

	def initialize(name, gender, ethnicity)
		@age = rand(18..65)
		@name = name
		@gender = gender
		@ethnicity = ethnicity
		@ccpref = "Coffee"
		@cases_solved = 0 
		@rank = "Constable"
		@alcohol_tol = 2
	end

	def promotion
		ranks = ["Retired", "Constable", "Sergeant", "Inspector", "Chief Inspector", "Superintendant", "Chief Superintendant"]
		previous_rank = ranks.index(@rank)
		if previous_rank == 0 
			puts "You are no longer on the force, you cannot advance in rank"
		elsif previous_rank == 6
			@rank = ranks[0]
			puts "You decide to retire from the force after an incredibly successful carreer"
		else
			@rank = ranks[previous_rank + 1]
			puts "Congratulations on your promotion #{@rank}!"
		end
	end

	def question(whom)
		puts "#{@name} decides to question #{whom}"
		puts "Where were you between 5 and 7 pm last friday evening?"
	end

	def paperwork
		puts "#{@name} has a metric ton of paperwork to complete"
	end

	def pub(drinks)
		ranks = ["Retired", "Constable", "Sergeant", "Inspector", "Chief Inspector", "Superintendant", "Chief Superintendant"]
		if ranks.index(@rank) > 4
			puts "I think that would be setting a poor example to your colleagues \nYou should try your hand at a round of golf with your peers"
		else 
			drinks.times do |i|
				if i == @alcohol_tol
					puts "#{@name} doesn't look so good, they decide to head home by cab because they know their limit"
					break
				end
				case i 
				when 9
					puts "#{@name} slams another drink"
					if ranks.index(@rank) == 0
						puts "#{@name} blacks out, you're a regular old boozer at this point..."
					else
						puts "#{@name} blacks out, this can't look good to their peers..."
					end
				when > 7
					puts "#{@name} pounds down another round \nthey appear very drunk at this point and are slurring their words"
				when > 4
					puts "#{@name} has themselves another round and thinks to themself\nI starting to consider this to be a rather expensive habit... \nThey appear quite well off and hiccuping"
				when > 1
					puts "#{@name} enjoys another fresh brew with the locals \nThey appear to be slightly tipsy and enjoying themself"
				when >= 0
					puts "#{@name} enjoys a round with friends"
				end  
			end
			@alcohol_tol += 1  
		end 
	end

	def solve_case
		@cases_solved += 1
	end

	def birthday
		@age += 1
	end

	def caffeine(drink)
		puts "#{@name} enjoys a fresh cup of #{@ccpref}"
		@ccpref = drink
	end

	attr_reader :ethnicity, :age, :cases_solved, :rank, :alcohol_tol
	attr_accessor :name, :gender, :ccpref

end


















